Ent - bug fixes
orangehrm/oxd pull request #116
Opened 2022-02-07 11:18 UTC by gayan-orangehrm

2022-02-08 16:28 UTC, lgtkaushalya requested changes

2022-02-09 05:04 UTC, gayan-orangehrm commented on components/src/core/components/Button/_mixins.scss
> +  &:hover {
As per discussion with Mike,
- Main, secondary, "label button" buttons should have the same hover-over effect when on focus
- For ghost buttons it should be 5% darker in border and the text label in it

2022-02-09 05:08 UTC, gayan-orangehrm commented on components/src/core/components/Button/button.scss
> +  :deep(svg) {
We are not using glass button in the application at the moment

2022-02-09 05:50 UTC, gayan-orangehrm commented on components/src/core/components/Calendar/calendar.scss
> +    margin: 0 !important;
fixed

2022-02-09 10:28 UTC, gayan-orangehrm commented on components/src/core/components/Sheet/_variables.scss
> +$oxd-sheet-padding-vertical: 1.2rem !default;
No it wont. they've already overridden it with 1rem

2022-02-09 10:28 UTC, gayan-orangehrm commented on components/src/core/components/FormDynamic/rules.ts
> +    "tel": (v: any) => !v || /^[0-9+()-\/]+$/.test(v) || 'Allows numbers and only + - / ( )',
renamed

2022-02-09 10:29 UTC, gayan-orangehrm commented on components/src/core/components/FormDynamic/rules.ts
> +    "name": (v: any) => (v && v.length <= 30) || 'Should be less than 30 characters',
fixed

2022-02-09 10:29 UTC, gayan-orangehrm commented on components/src/core/components/Button/Button.vue
> +        class="oxd-button-icon oxd-button-icon-right"
fixed

2022-02-09 11:55 UTC, gayan-orangehrm commented on components/src/core/components/Button/_mixins.scss
> +  :deep(svg) {
He has provided a fix offline

2022-02-09 15:10 UTC, merged